--Created by Wishbone https://github.com/SaintWish for Dawn of Resdayn RP
--All rights reserved.
local config = {}

config.enabled = true

config.hunger = true
config.thirst = true
config.fatigue = false --enable at your own risk, the logic is there but resting won't work correctly.

config.debuff = false --doesn't properly work yet?

config.debug = true

config.prefix = "[Player-Needs]"
config.prefixColor = color.Cyan
config.msgColor = color.LightCyan

config.hungerTimer = 300000 --in milseconds
config.thirstTimer = 300000 --in milseconds
config.fatigueTimer = 300000 --in milseconds
config.restTimer = 300000 --in milseconds, how long should resting last

config.hungerDecrement = 2 --how much it decrease each time the timer expires.
config.thirstDecrement = 3 --how much it decrease each time the timer expires.
config.fatigueDecrement = 2 --how much it decrease each time the timer expires.
config.midCount = 50 --at what amount should it give you warning for mid range
config.lowRange = 10 --at what range should it be critical

--Cells players are allowed to rest in.
config.restCells = {"Balmora, South Wall Cornerclub"}

--Add items by doing ["itemid"] = needs increment amount
config.foodItems = {
  ["ingred_ash_yam_01"] = 10,
  ["ingred_comberry_01"] = 5,
  ["ingred_bread_01"] = 50,
  ["ingred_crab_meat_01"] = 50,
  ["ingred_daedras_heart_01"] = 15,
  ["ingred_hound_meat_01"] = 50,
  ["food_kwama_egg_02"] = 50,
  ["ingred_kwama_cuttle_01"] = 10,
  ["ingred_rat_meat_01"] = 25,
  ["ingred_scrib_jelly_01"] = 10,
  ["food_kwama_egg_01"] = 25,
  ["ingred_trama_root_01"] = 5,
  ["ingred_6th_corprusmeat_05"] = 10,
  ["ingred_6th_corprusmeat_01"] = 10,
  ["ingred_6th_corprusmeat_06"] = 10,
  ["ingred_6th_corprusmeat_03"] = 10,
  ["ingred_6th_corprusmeat_07"] = 10,
  ["ingred_6th_corprusmeat_02"] = 10,
  ["ingred_6th_corprusmeat_04"] = 10,
  ["ingred_bread_01_UNI2"] = 50,
  ["ingred_human_meat_01"] = 50,
  ["ingred_bread_01_UNI3"] = 25,
  ["ingred_corkbulb_root_01"] = 5,
  ["ingred_willow_anther_01"] = 10,
  ["ingred_wickwheat_01"] = 5,
  ["ingred_moon_sugar_01"] = 5,
  ["ingred_kresh_fiber_01"] = 10,
  ["ingred_saltrice_01"] = 5,
  ["ingred_scuttle_01"] = 15,
  ["ingred_hackle-lo_leaf_01"] = 5,
  ["ingred_chokeweed_01"] = 5,
  ["ingred_marshmerrow_01"] = 5,
  ["ingred_scathecraw_01"] = 10,
  ["t_ingfood_fishslaughterdried_03"] = 35,
  ["t_ingfood_cheesecolovian_01"] = 20,
  ["t_ingfood_cookie_02"] = 10,
  ["t_ingfood_fishspr_01"] = 40,
  ["t_ingfood_onion_01"] = 5,
  ["t_ingfood_apple_01"] = 10,
  ["t_ingfood_breadcolovian_01"] = 40,
  ["t_ingfood_breadcolovian_02"] = 20,
  ["t_ingfood_honey_01"] = 20,
  ["t_ingfood_fishslaughterdried_01"] = 50,
  ["t_ingfood_fig_drid_01"] = 15,
  ["t_ingfood_ironrye_01"] = 10,
  ["t_ingfood_eggchicken_01"] = 20,
  ["t_ingfood_garlic_01"] = 5,
  ["t_ingfood_meatbeef_01"] = 20,
  ["t_ingfood_fishlongfinfilet_01"] = 50,
  ["t_ingfood_fishstrid_01"] = 20,
  ["t_ingflor_ladysmantle_01"] = 5,
  ["t_ingfood_indureta_01"] = 10,
  ["t_ingfood_cookie_01"] = 20,
  ["t_ingfood_grape_01"] = 10,
  ["t_ingfood_meatmutton_01"] = 50,
  ["t_ingfood_meatrat_01"] = 30,
  ["t_ingfood_potato_01"] = 40,
  ["t_ingfood_leek_01"] = 20,
  ["t_ingflor_thungleweed_01"] = 10,
  ["t_ingflor_goldenrod_01"] = 10,
  ["t_ingflor_bloodlilypod_01"] = 10,
  ["t_ingfood_meathorse_01"] = 75,
  ["t_ingfood_meatchicken_01"] = 40,
  ["t_ingfood_wheat_01"] = 20,
  ["t_ingfood_appleskyrim_01"] = 20,
  ["t_ingfood_fig_01"] = 20,
  ["t_ingfood_blackberry_01"] = 5,
  ["t_ingflor_tinderpolypore_01"] = 10,
  ["t_ingflor_foxglovenectar_01"] = 5,
  ["t_ingflor_ladyssmock_01"] = 5,
  ["t_ingflor_cairnbolete_01"] = 10,
  ["t_ingflor_wispstalk_01"] = 15,
  ["t_ingfood_meatguar_01"] = 20,
  ["t_ingfood_eggornada_01"] = 15,
  ["t_ingfood_scribpie_01"] = 50,
  ["t_ingfood_breaddeshaan_02"] = 50,
  ["t_ingfood_meatnixhoundroast_01"] = 40,
  ["t_ingfood_meatornada_01"] = 20,
  ["ingred_scales_01"] = 5,
  ["t_ingflor_ironwoodnut_01"] = 10,
  ["t_ingfood_snowberry_01"] = 10,
  ["t_ingflor_cowbell_01"] = 10,
  ["t_ingflor_tawnyfunnelcap_01"] = 20,
  ["ingred_gravetar_01"] = 5,
  ["t_ingflor_lizardfootextract_01"] = 10,
  ["t_ingflor_canisroot_01"] = 5,
  ["t_ingfood_bridethornberry_01"] = 10,
  ["t_ingfood_fishcoddried_01"] = 40,
  ["t_ingfood_fishsalmon_01"] = 50,
  ["t_ingfood_meatvenison_01"] = 50,
  ["t_ingfood_meatboar_02"] = 60,
  ["t_ingfood_breadflat_01"] = 30,
  ["t_ingfood_radish_01"] = 20,
  ["t_ingflor_cabbage_01"] = 30,
  ["t_ingfood_grapewrothgarian_01"] = 20,
  ["bs_i_fishnohead_01"] = 30,
  ["bs_ndib_ingred_whitebellpetals"] = 10,
  ["bs_i_fishhead_02"] = 20,
  ["bs_i_fishhead_01"] = 20,
  ["bs_i_barley_02"] = 15,
  ["bs_objcotton2_mw"] = 30,
  ["bs_objcotton_mw"] = 30,
  ["bs_eggy_plants_tri2_i_mw"] = 30,
  ["bs_tad_grapes_white"] = 20,
  ["bs_i_honeycomb1_1"] = 30,
  ["bs_i_briar_berries_1"] = 20,
  ["bs_m_pie_ing"] = 50,
  ["bs_i_sump_plant3e_shroom"] = 20,
  ["bs_i_bell_shroom_cap2_s"] = 30,
  ["bs_ing_sw_cheese1"] = 40,
  ["bs_mushrooms_610_sg2_i"] = 20, -- Shadowcap
  ["bs_ndib_ingred_mooncap_flesh"] = 30, -- Poor Man's Chalice
  ["bs_i_flour_sack01"] = 40,
  ["bs_ing_ched_cheese10"] = 40,
  ["bs_ing_shp_cheese1b"] = 30,
  ["bs_i_boletus_shroom_rd"] = 20, -- Bloody Crown
  ["bs_tad_grapes_red"] = 30, -- Vermilion Grapes
  ["bs_i_honeycomb1_0"] = 50,
  ["bs_tad_yeast_2"] = 10,
  ["bs_i_pass_plant_fruit"] = 40, -- Caprice Blossom Fruit
  ["bs_pumpkin_sm_m2"] = 30, -- Tumescent Melon
  ["bs_st_fryingsausage2_mw"] = 30,
  ["bs_broiler_mw"] = 50,
  ["ingred_meadow_rye_01"] = 40,
  ["bs_st_bloodsausage_mw"] = 30,
  ["bs_i_sweetcake_03b"] = 50,
  ["bs_shroom_brown_ing_011"] = 20, -- Rusted Armillaria
  ["bs_i_roasted_meat"] = 60, -- Roasted Boar Meat
  ["bs_i_fishhead_soup"] = 50,
  ["bs_i_fishnohead_02"] = 30
}

--Add items by doing ["itemid"] = needs increment amount
config.drinkItems = {
  ["potion_local_liquor_01"] = 25,
  ["Potion_Local_Brew_01"] = 50,
  ["potion_cyro_whiskey_01"] = 25,
  ["potion_ancient_brandy"] = 25,
  ["potion_cyro_brandy_01"] = 25,
  ["potion_nord_mead"] = 50,
  ["potion_comberry_brandy_01"] = 25,
  ["potion_comberry_wine_01"] = 25,
  ["potion_skooma_01"] = 10,
  ["p_vintagecornberrybrandy1"] = 50,
  ["potion_local_brew_01"] = 50,
  ["bs_m_bottle_cyrol_3"] = 50,
  ["t_rga_drink_winesutchgonogro_01"] = 50,
  ["t_rga_drink_winesutchtalan_01"] = 50,
  ["t_imp_drink_wineplallovin_01"] = 50,
  ["t_imp_drink_winetamikaelr_01"] = 50,
  ["t_imp_drink_winewolfsbl_01"] = 50,
  ["t_imp_drink_cherrybrandy_01"] = 50,
  ["t_imp_drink_aleakul_01"] = 50,
  ["t_imp_drink_winefreeestat_01"] = 50,
  ["t_imp-drink_cideraliyew_01"] = 50,
  ["t_imp_drink_winesuriliebr_01"] = 50,
  ["t_imp_drink_winetwinmoon_01"] = 50,
  ["t_imp_drink_ricebeermori_01"] = 50,
  ["t_imp-drink_wineblackhill_01"] = 50,
  ["t_imp_drink_winesweet"] = 50,
  ["t_imp_drink_winesour"] = 50,
  ["t_imp_drink_winerufinoclr_01"] = 50,
  ["t_nor_drink_winereach_01"] = 50,
  ["bs_alch_bottle_wine5_1"] = 50,
  ["bs_m_com_tankard_full2"] = 50, -- Frothy Wench Ale
  ["bs_alch_bottle_wine_fat1a"] = 50,
  ["bs_potion_bs_bottle5b1"] = 40, -- Taen
  ["bs_m_bottle_cryol_3"] = 50,
  ["bs_m_bottle_liquer1"] = 60, -- Stros M'kai Rum
  ["bs_potion_bs_bottle13_6hb"] = 50, -- Herne's Blood Bourbon
  ["bs_potion_bs_bottle13_6hr"] = 50, -- Honey Rye
  ["bs_m_bottle_tan_uni1_0"] = 50, -- Sedrisa's Salacious Tincture
  ["bs_alch_bottle_wine3"] = 50, -- Port Wine
  ["bs_alch_bottle_ale_12blu"] = 40, -- Vigilance Ale
  ["bs_alch_bottle_ale_1gld_2"] = 50, -- Alinor Golden Ale
  ["bs_tr_flask_jagga"] = 60,
  ["bs_potion_bs_bottle6_1"] = 50, -- Nightmask
  ["bs_sbottle02a_mw"] = 50, -- Gluttonous Brown Ale
  ["bs_sbottle03a_mw"] = 50 -- Sparkling Honeydew
}

return config
